### ISSUE TITLE
change registry class

### ISSUE THREAD

**Issue by JBlond** [DigiLive/resetPhpStormEvaluationPeriod#2]
Why don't you change the registry class to DigiLive/windows-registry ?

**Comment by DigiLive** [comment]
At the time of the current latest release, I was still developing this project and made me debug the windows-registry package.

I'm ready for a next release which will use the digilive/windows-registry package.

Thanks for your interest.

**Comment by DigiLive** [comment]
https://github.com/DigiLive/resetPhpStormEvaluationPeriod/releases/tag/v1.0.1-alpha
